### ISSUE TITLE
2.x Branch

### ISSUE THREAD

**Issue by ravage84** [robwilkerson/CakePHP-Audit-Log-Plugin#106]
According to https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin#cakephp-2x

> The 2.x branch contains a stable version, but is not up to date.

So what's the point of it? It's probably a relict of when the master branch was planned to be the active development branch for the CakePHP 3.x plugin version.

I would remove that stale branch. It could confuse people.

The only downside I see, is that it could break the composer installation of some people relying on this (obviously outdated) branch.

**Comment by xhs345** [comment]
You're correct in you assumption and I agree with removing it. 

This would be a decision @robwilkerson has to make

**Comment by robwilkerson** [comment]
@ravage84 & @xhs345 : You all have been doing a great job keeping this project alive. I'd trust your judgment on a decision like this far more than I'd trust my own given my current distance from Cake. 

I've been following along with the updates, but mostly because I'm pleased to see that the project has been helpful, has gained some small measure of popularity and has continued to have legs after I let it sit idle for too long. 

Please proceed as you see fit and thanks for continuing to support and improve the project.

**Comment by xhs345** [comment]
@robwilkerson I'm also gad about all the progress that is happening thanks to @ravage84 

I mentioned you because I actually  don't have the permission to delete the branch :)

**Comment by robwilkerson** [comment]
@xhs345 Hmmm. Well, let me see what I can do about that...

**Comment by robwilkerson** [comment]
@xhs345 It wasn't a permissions issue, but the branch was protected. See if you can delete it now.

**Comment by xhs345** [comment]
Yup, worked. Thanks!
