### ISSUE TITLE
currentUser code

### ISSUE THREAD

**Issue by chris-sharman** [robwilkerson/CakePHP-Audit-Log-Plugin#35]
couldn't get the currentUser functionality working as suggested.

eventually put:
    public function currentUser() // for AuditLog.Auditable behavior
    {
      return CakeSession::read("Auth.User");
    }
into AppModel (note public, not protected as suggested); and nothing required in AppController.

Thanks
Chris

**Comment by L1lle** [comment]
I ran into the same problem and added these line to AppModel.php and AppTable.php (because I use Entities). I wanted to stick to the basic AuthComponent without reading from Session directly. With my function I could event return a different  user columns like "uuid". 

The function has to be public like @chris-sharman suggested.

    public function currentUser() {
		
		return array(
			'id' => AuthComponent::user('id'),
		);
	}

**Comment by xhs345** [comment]
I updated the Readme, thanks!
