### ISSUE TITLE
ENHANCEMENT: summary in AuditDelta

### ISSUE THREAD

**Issue by fr0z3nfyr** [robwilkerson/CakePHP-Audit-Log-Plugin#39]
At present, the `AuditDelta` model stores `property_value`, `old_value` and `new_value` as available in `$this->request->data`. However, this becomes very tedious to audit the changes that has HABTM associations. For example, if on `Task` model, if the assignment of task changes from `user_id 1 to 5`, the log should save the `display name` of `User` model in `old_value` and `new_value`, while the alias name of associated model, i.e., `Assignee` (alias for User model to manage assignments) should be saved in `property_value`.

This can probably be achieved by modifying the `afterSave()` in behavior. I started editing the behavior to apply a quick hack for my situation but it failed to save anything after that. So I had to revert the changes due to lack of time. Thought I should share the idea with you so that you can pursue it further for actual implementation. A gist of my code is below:
```PHP
$btModels = $Model->belongsTo; // List of belongsTo Models with association info. I needed on belongsTo associations in my audit log
$btm = $this->_btModel($property, $btModels);
$pn = Inflector::humanize($property);
$ov = $Model->$btm->find('list', array('conditions' => array($btm.'.id' => $this->_original[$Model->alias][$property])));
$nv = $Model->$btm->find('list', array('conditions' => array($btm.'.id' => $value)));

$delta = array(
	'AuditDelta' => array(
	'property_name' => $pn,
	'old_value'     => $ov,
	'new_value'     => $nv
	)
);
/*********************************************************************/
/* Above code was substituted with the actual $delta in the behavior */
/*********************************************************************/

/* A quick and dirty workaround to be used to extract HABTM details */
private function _btModel($str, $array) {
	foreach ($array as $key => $val) {
		if ($val['foreignKey'] === $str) {
			return $key;
		}
	}
	return null;
}
```

I'll be more than happy to contribute if you are willing to include such enhancement. Meanwhile, if you can point out where in above code I may be doing wrong to achieve this, I will be thankful.

Regards

**Comment by fr0z3nfyr** [comment]
Well, I somehow forgot about this completely, this open issue came to my notice today so I thought I share the solution I used to address this need.

I'm [pushed a commit](https://github.com/robwilkerson/CakePHP-Audit-Log-Plugin/pull/62/commits/770b72a0e9547ed9b52294126c4d03cfe71c3d67) for you to review and include in the behaviour (2.x).

**Comment by fr0z3nfyr** [comment]
Although, I do understand that it may not be a very good idea for cases where the actual value may change, for example, a manager's name. In such a case, while manager_id will be useful to get current value of manager's name but saving manager's name today may not match with manager's updated name tomorrow. I think, I will add this as a configurable option in next commit.

**Comment by ravage84** [comment]
I got a few issues with the idea and the related PR:

1. It changes the default behavior instead of being configurable (at the moment)
2. It changes the current behavior in a non-backward compatible way, which is a generally a no-go
3. Saving a display name, that could change after it gets logged isn't the problem. The problem IMHO is that it replaces the storage of a value that is more valuable. An audit log is often done for, you guessed it, auditing data manipulations. Saving the current display name  to the logs at a certain point in time is fine, but saving the ID is much more valuable as it is (normally) unique and does not change over time.
4. Due to my various changes, your PR #62 can't be merged anymore

But your proposal made me think and I thought about alternative storage solutions:
1. Store the display names in two separate fields in ``audit_deltas``. But I don't like this as these fields won't get used in non-foreign key cases, so it's wasted DB space (& potentially performance)
2. Store the display names in a separate ``audit_deltas`` record, alongside the foreign keys. But I don't like this either, as would lead to **many** additional ``audit_deltas`` records. Though, this could be a viable solution, as long as it was configurable.

Stillwas not sold on either solution, so I was looking for another way, to improve the readability of those cases.
Then it came to my mind that this probably should not be solved in the behavior but could be solved in the ``AuditDelta`` model (does not exist yet), at least to some extend.

What if we just save the foreign key as we do now but use the data available (foreign key value in ``audit_deltas`` & property name in ``audits``) to try to get the (current) display name of the referenced record?
This could be done in ``AuditDelta::afterFind()``, for example by inflecting the model name through the property name and fetching the record of that model through the foreign key value stored.

I know there are a few pitfalls, either:
1. The foreign key field could be named unlike its referenced table
2. The referenced record in the foreign table could be deleted, too
3. Probably more

Nonetheless, I see this solution to be superior, since it does not break anything, does not waste DB space and it tries to solve the problem where it is and not somewhere else.

**Comment by ravage84** [comment]
@xhs345 closing this, as I pointed out better alternatives?
@fr0z3nfyr feel free to base new changes upon my work from #102.

**Comment by xhs345** [comment]
Yes, the PR should be a workable solution for now

**Comment by fr0z3nfyr** [comment]
@ravage84 - Valid points.
For the pitfall #2 you mentioned, I think the best approach will be bind it with `SoftDelete`, i.e, this data will be saved only if you have `SoftDelete` loaded in the model (being "hyper"-audited). I'm looking into passing `config` settings while noting all other suggestions made by you, working on dev-master branch.
