### ISSUE TITLE
No 3.x Support :(

### ISSUE THREAD

**Issue by adam-je** [robwilkerson/CakePHP-Audit-Log-Plugin#40]
No 3.x Support :(

**Comment by robwilkerson** [comment]
At the risk of sounding glib, pull requests would be much appreciated. :-) 

The less jackass-y version is that I just don't have any projects running Cake 3 and I'm not sure if/when I will. I'll probably need community support to put this in place. I wish I had better news, but I'll let you know if anything changes.

**Comment by adam-je** [comment]
Thank you. My skills are still premature to support the development, but will "keep the watch" til then.

**Comment by angelxmoreno** [comment]
@robwilkerson i don't know where you get that asking for PRs sounds jackass-y. We did not pay you for this and it saved us time. Least anyone can do for an open source developer is send a PR. Ain't no shame in asking.

**Comment by robwilkerson** [comment]
@angelxmoreno Yeah, I know that's true, strictly speaking. At the same time, though, I'm basically telling him that I'm not going to put any effort into his request and that could come off as dismissive or just plain "jackass-y".

The fact is, although this plugin has a very small community, it's their contributions rather than mine that have kept it relevant for a pretty long time now (as you probably know, having been around for a while) and I feel a tremendous amount of appreciation for that and would never want to do anything to actively discourage continued participation. :-)

**Comment by angelxmoreno** [comment]
very well said.

**Comment by xhs345** [comment]
Hi. 
Because I wanted to learn a bit about CakePHP3 I started looking into the migration of the Plugin. After doing some research and testing I realized that because of all the ORM changes (http://book.cakephp.org/3.0/en/appendices/orm-migration.html) an almost complete rewrite of the plugin will be necessary.

I already created the migration scripts to replace the schema files and fixed the director layout, but without the rest working these changes are not that useful.

**Comment by robwilkerson** [comment]
@xhs345 Fair enough. We have some options, then. I'll be happy to add anyone involved in the 3.0 changes as a collaborator on this project or we could make this project the canonical one for versions < 3.x and someone who is more actively working with Cake 3 can start anew in their own repository.

Thoughts?

**Comment by inigoflores** [comment]
I will be happy to contribute as soon as I gain enough experience with CakePHP 3.

**Comment by xhs345** [comment]
@robwilkerson As it currently stands there seems to be no one who wants to take the lead on the project, so I guess there is no harm in starting with some groundwork in this repository. If you want to add me I can update the readme and add the few files I created

**Comment by robwilkerson** [comment]
That sounds great to me, @xhs345 . What I think I'd like to do, since you all expect this to be a complete rewrite, is to create a 3.x working branch. Do all 3.x work there and then, when the consensus is that it's ready, we'll merge that into master. Thoughts?

**Comment by xhs345** [comment]
@robwilkerson Yea, I think this is better as well. So put the 2.x branch back into the master and create a new 3.x-dev branch? Then once 3.x is ready the 2.x Master can be branched out again.  I would think that would be the cleanest solution

**Comment by robwilkerson** [comment]
@xhs345 I'm not sure it  really matters whether we remove the `2.x` branch, but we can certainly do that if you'd rather. At any rate, I'll definitely create the new dev branch. For further clarity, maybe I'll call it `dev-3.x`. I'll also give you write perms to the repo.

Should others choose to join you in contributing, I'll open it up to them as well pending your request/approval.

Thanks so much for continuing the development.

**Comment by xhs345** [comment]
@robwilkerson Thanks a lot! I'll see what I can do, so no promises yet.

Regarding the `2.x` / `Master` branch: There are already some differences because I pushed my fix to the 2.x branch but the composer file was added for the master. Just feel that this could be confusing for users.

**Comment by robwilkerson** [comment]
Ah yeah. I created the `dev-3.x` from master. Any reason we can't merge `2.x` back into master to even them out?

**Comment by xhs345** [comment]
Yea, merging it back was what I had in mind. Just so there is less replication of code. 
Once 3.x is ready and 2.x discontinued we could move the (2.x)master to a 2.x branch again and dev-3x to the master...
But this is all minor and really up to you

**Comment by robwilkerson** [comment]
I don't know that we can discontinue the `2.x` branch since I suspect there are still a number of 2.x projects out there. That said, at this point, I don't see any reason that the `master`, `2.x` and `dev-3.x` shouldn't be identical. 

Why don't we start by making that happen and the continue development on the `dev-3.x` branch? Want to make that your first official act as a contributor and then close this ticket? :-)

**Comment by xhs345** [comment]
Sorry for being not clear. To phrase it in another way: I just thought the 2.x development should be continued in the master branch until the 3.x version is usable.

Gonna commit a few thing to the dev branch soon :). Wasn't my intention to keep you busy with this

**Comment by xhs345** [comment]
`CakePHP 3.x` development started in `dev-3.x` branch

**Comment by adam-je** [comment]
:)
