### ISSUE TITLE
String no longer supported from Cake 2.7

### ISSUE THREAD

**Issue by jeanloup** [robwilkerson/CakePHP-Audit-Log-Plugin#41]
I scratched my head for hours before finally working this out.

I run CakePHP 2.7 and on line 21 of the AuditableBehavior.php file there is a declaration using String::uuid() which fails all attempts at adding, editing etc.

String is deprecated from Cake 2.7 and should be replaced by CakeText instead. May I suggest a check whether the model String exists and if not use CakeText instead in the request_id() method?

**Comment by robwilkerson** [comment]
I'm down. Alternatively, we could create a branch for the existing version for 2.x and use master for 3.x changes. I don't use Cake all that often any longer, so I'm open to suggestions on this.

Thanks!

**Comment by xhs345** [comment]
Just saw you created a 2.x branch right now, which might be confusing looking at this issue. I think the current 2.x branch should be 2.0 - 2.6. Maybe 2.7+ and 3*x can both share the master in the future, but I'm not sure about that

**Comment by robwilkerson** [comment]
I just updated #45 (which has a pull request fixing this) to indicate my preference that the `2.x` branch code be compatible with all version of Cake 2.x rather than have a specific branch that essentially supports this change only. Preferable, I think, to have a quick test in the code to see whether CakeText is available. We can remove that test on the master branch (now dedicated to 3.x) to simplify the code.

**Comment by xhs345** [comment]
Yes, that sounds like a good idea

**Comment by inigoflores** [comment]
I guess this is now fixed in 2.x.
